/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as erc721PermitEverywhereSol from "./ERC721PermitEverywhere.sol";
export { ERC20PermitEverywhere__factory } from "./ERC20PermitEverywhere__factory";
