/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as erc721PermitEverywhereSol from "./ERC721PermitEverywhere.sol";
export type { erc721PermitEverywhereSol };
export type { ERC20PermitEverywhere } from "./ERC20PermitEverywhere";
export * as factories from "./factories";
export { ERC20PermitEverywhere__factory } from "./factories/ERC20PermitEverywhere__factory";
export type { ERC721PermitEverywhere } from "./ERC721PermitEverywhere.sol/ERC721PermitEverywhere";
export { ERC721PermitEverywhere__factory } from "./factories/ERC721PermitEverywhere.sol/ERC721PermitEverywhere__factory";
export type { IERC721 } from "./ERC721PermitEverywhere.sol/IERC721";
export { IERC721__factory } from "./factories/ERC721PermitEverywhere.sol/IERC721__factory";
